### ISSUE TITLE
It is not doing a discount.

### ISSUE THREAD

**Issue by demirmusa** [stripe-samples/charging-for-multiple-plan-subscriptions#4]
Hi. Not sure but it seems like it is not giving a discount. 

Tested on https://8omeu.sse.codesandbox.io.

![Screenshot_5](https://user-images.githubusercontent.com/48536631/69149919-9400eb00-0ae8-11ea-840b-44f258e05884.png)

**Comment by ctrudeau-stripe** [comment]
Thank you for letting us know. I've updated the sandbox to the latest which applies the discounts. 

https://bio87.sse.codesandbox.io/
