### ISSUE TITLE
Forking the Node implementation on CodeSandbox fails

### ISSUE THREAD

**Issue by lgs** [stripe-samples/charging-for-multiple-plan-subscriptions#9]
# Build fails

## Forking the Node implementation on [CodeSandbox](https://codesandbox.io/s/stripe-billing-multiplan-subscription-quickstart-zph6v) fails with 502: Bad Gateway

In the console you get the following:
```
$ node server/node/server.js
/sandbox/node_modules/serve-static/index.js:40
    throw new TypeError('root path required')
    ^
error Command failed with exit code 1.
```

## To Reproduce

Fork and see

**Comment by cjavilla-stripe** [comment]
Thanks for the report, @lgs. This sample is deprecated. Please use: https://github.com/stripe-samples/subscription-use-cases/.
